# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Distributed Web Primer
tagline:          'How to lock the web open'
description:      'Tutorials and presentations explaining the technical ideas behind the distributed web.'
url:              http://swadeshi.github.io/distributed-web-primer/
baseurl:          /distributed-web-primer

author:
  name:           'Matt Zumwalt'
  url:            https://twitter.com/flyingzumwalt

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/swadeshi/distributed-web-primer
