# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Distributed Data Primer
tagline:          'How to lock the web open'
description:      'A set of tutorials and presentations explaining the technical ideas behind distributed data.'
url:              http://swadeshi.github.io/distributed-data-primer/
baseurl:          /

author:
  name:           'Matt Zumwalt'
  url:            https://twitter.com/flyingzumwalt

gems: [jekyll-paginate]

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/swadeshi/distributed-data-primer
